version: "3.9"
services:
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: postgres
  commcare_export_json:
    build: .
    environment:
      - CC_HQ
      - CC_USER
      - CC_APIKEY
      - CC_PROJECT
      - S3_DEST
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
#    volumes:
#      - ~/.aws:/root/.aws
