version: "3.9"
services:
  postgres:
    image: "postgres:alpine"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ~/.aws:/root/.aws
  commcare_export_json:
    build: .
    environment:
      - CC_USER
      - CC_APIKEY
      - CC_PROJECT
      - S3_DEST
